name: Browser antibot tests

on:
  push:
    paths:
      - '**/*.py'
      - 'requirements.txt'
      - '.github/workflows/browser-antibot.yml'
  pull_request:

jobs:
  run-browser-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies & Playwright
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run browser-antibot tests
        run: pytest tests/test_browser_antibot.py
